"""empty message

Revision ID: f6b6cad07606
Revises: 84b0f77d8237
Create Date: 2018-06-07 16:36:25.032061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6b6cad07606'
down_revision = '84b0f77d8237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_disbursements', 'disb_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('projects', 'proj_approval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'disbursements_approval_rights',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('users', 'user_approver_rights',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    #op.add_column('warehouse_receipts', sa.Column('receipt_total_cost', sa.Numeric(), nullable=False))
    op.alter_column('warehouse_receipts', 'receipt_barcode',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.VARCHAR(40),
               nullable=True)
    op.drop_column('warehouse_receipts', 'receipt_unit_cost')
    op.alter_column('warehouse_reqs', 'req_approval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('warehouse_users', 'user_approver_rights',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse_users', 'user_approver_rights',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('warehouse_reqs', 'req_approval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('warehouse_receipts', sa.Column('receipt_unit_cost', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.alter_column('warehouse_receipts', 'receipt_barcode',
               existing_type=sa.VARCHAR(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    op.drop_column('warehouse_receipts', 'receipt_total_cost')
    op.alter_column('users', 'user_approver_rights',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('users', 'disbursements_approval_rights',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('projects', 'proj_approval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('project_disbursements', 'disb_status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
